name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{secrets.GCP_PROJECT}}
        credientials: ${{secrets.GCP_CREDENTIALS}}
    - uses: actions/checkout@v2
    - name: Deploy an App Engine app
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml 
        service: python-app
        version: v12
        project_id: ${{ secrets.GCP_PROJECT}}
        credentials: ${{secrets.GCP_CREDENTIALS}}
